package com.example.piagent.session;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * AgentSession 会话模型测试
 *
 * 测试目的：
 * 1. 验证会话对象的创建和属性访问
 * 2. 验证消息添加功能
 * 3. 验证会话 ID 生成规则
 */
@DisplayName("AgentSession 会话模型测试")
class AgentSessionTest {

    @Nested
    @DisplayName("创建会话测试")
    class CreateSessionTest {

        @Test
        @DisplayName("应该创建带自定义 ID 的会话")
        void shouldCreateSessionWithCustomId() {
            AgentSession session = AgentSession.builder()
                    .id("session_001")
                    .name("测试会话")
                    .build();

            assertThat(session.getId()).isEqualTo("session_001");
            assertThat(session.getName()).isEqualTo("测试会话");
            assertThat(session.getMessages()).isEmpty();
        }

        @Test
        @DisplayName("应该创建不带 ID 的会话（自动生成）")
        void shouldCreateSessionWithAutoGeneratedId() {
            AgentSession session = AgentSession.builder().build();

            assertThat(session.getId()).isNotNull();
            assertThat(session.getId()).isNotEmpty();
        }

        @Test
        @DisplayName("应该创建带默认值的会话")
        void shouldCreateSessionWithDefaultValues() {
            AgentSession session = AgentSession.builder().build();

            assertThat(session.getMessages()).isNotNull();
            assertThat(session.getMessages()).isEmpty();
            assertThat(session.getCreatedAt()).isNotNull();
            assertThat(session.getUpdatedAt()).isNotNull();
        }
    }

    @Nested
    @DisplayName("添加消息测试")
    class AddMessageTest {

        @Test
        @DisplayName("应该成功添加消息到会话")
        void shouldAddMessageToSession() {
            AgentSession session = AgentSession.builder()
                    .id("session_001")
                    .build();
            var message = com.example.piagent.message.Message.builder()
                    .role(com.example.piagent.message.MessageRole.USER)
                    .content("你好")
                    .build();

            session.addMessage(message);

            assertThat(session.getMessages()).hasSize(1);
            assertThat(session.getMessages().get(0).getContent()).isEqualTo("你好");
        }

        @Test
        @DisplayName("应该能添加多条消息")
        void shouldAddMultipleMessages() {
            AgentSession session = AgentSession.builder()
                    .id("session_001")
                    .build();

            session.addMessage(com.example.piagent.message.MessageFactory.createUserMessage("你好"));
            session.addMessage(com.example.piagent.message.MessageFactory.createAssistantMessage("你好，我是助手"));
            session.addMessage(com.example.piagent.message.MessageFactory.createUserMessage("天气如何"));

            assertThat(session.getMessages()).hasSize(3);
        }

        @Test
        @DisplayName("添加消息后更新时间戳")
        void shouldUpdateTimestampAfterAddingMessage() {
            AgentSession session = AgentSession.builder().build();
            var initialUpdateTime = session.getUpdatedAt();

            try {
                Thread.sleep(10);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }

            session.addMessage(com.example.piagent.message.MessageFactory.createUserMessage("新消息"));
            assertThat(session.getUpdatedAt()).isAfterOrEqualTo(initialUpdateTime);
        }
    }

    @Nested
    @DisplayName("获取消息历史测试")
    class GetMessageHistoryTest {

        @Test
        @DisplayName("应该返回完整的消息历史")
        void shouldReturnFullMessageHistory() {
            AgentSession session = AgentSession.builder().id("session_001").build();
            session.addMessage(com.example.piagent.message.MessageFactory.createUserMessage("消息1"));
            session.addMessage(com.example.piagent.message.MessageFactory.createAssistantMessage("回复1"));

            var messages = session.getMessages();

            assertThat(messages).hasSize(2);
        }

        @Test
        @DisplayName("空会话应该返回空消息列表")
        void shouldReturnEmptyListForEmptySession() {
            AgentSession session = AgentSession.builder().build();

            assertThat(session.getMessages()).isEmpty();
        }
    }
}
