package com.example.piagent.agent;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Task 任务模型测试
 */
@DisplayName("Task 测试")
class TaskTest {

    @Nested
    @DisplayName("创建任务测试")
    class CreateTaskTest {

        @Test
        @DisplayName("应该创建任务并自动生成 ID")
        void shouldCreateTaskWithAutoGeneratedId() {
            Task task = Task.create("测试任务");

            assertThat(task.getId()).isNotNull();
            assertThat(task.getDescription()).isEqualTo("测试任务");
            assertThat(task.getStatus()).isEqualTo(Task.TaskStatus.CREATED);
        }

        @Test
        @DisplayName("应该创建带父子关系的任务")
        void shouldCreateTaskWithParent() {
            Task parent = Task.create("父任务");
            Task child = Task.create("子任务", parent.getId());

            assertThat(child.getParentTaskId()).isEqualTo(parent.getId());
        }
    }

    @Nested
    @DisplayName("任务状态转换测试")
    class TaskStatusTransitionTest {

        @Test
        @DisplayName("应该正确转换到 RUNNING 状态")
        void shouldTransitionToRunning() {
            Task task = Task.create("测试任务");

            task.start();

            assertThat(task.getStatus()).isEqualTo(Task.TaskStatus.RUNNING);
            assertThat(task.getStartedAt()).isNotNull();
            assertThat(task.isRunning()).isTrue();
        }

        @Test
        @DisplayName("应该正确转换到 COMPLETED 状态")
        void shouldTransitionToCompleted() {
            Task task = Task.create("测试任务");

            task.complete("任务结果");

            assertThat(task.getStatus()).isEqualTo(Task.TaskStatus.COMPLETED);
            assertThat(task.getResult()).isEqualTo("任务结果");
            assertThat(task.getCompletedAt()).isNotNull();
            assertThat(task.isCompleted()).isTrue();
        }

        @Test
        @DisplayName("应该正确转换到 FAILED 状态")
        void shouldTransitionToFailed() {
            Task task = Task.create("测试任务");

            task.fail("错误信息");

            assertThat(task.getStatus()).isEqualTo(Task.TaskStatus.FAILED);
            assertThat(task.getError()).isEqualTo("错误信息");
            assertThat(task.getCompletedAt()).isNotNull();
            assertThat(task.isFailed()).isTrue();
        }
    }

    @Nested
    @DisplayName("任务状态查询测试")
    class TaskStatusQueryTest {

        @Test
        @DisplayName("新任务应该处于 CREATED 状态")
        void newTaskShouldBeCreated() {
            Task task = Task.create("测试任务");

            assertThat(task.getStatus()).isEqualTo(Task.TaskStatus.CREATED);
            assertThat(task.isRunning()).isFalse();
            assertThat(task.isCompleted()).isFalse();
            assertThat(task.isFailed()).isFalse();
        }
    }
}
